### ISSUE TITLE
Lighthouse Test is 0 performance - everything else >= 91

### ISSUE THREAD

**Issue by alvirtuoso** [Shyam-Chen/Vue-Fullstack-Starter#26]
lighthouse tested the prod-mode link. Does any one has different result?

**Comment by Shyam-Chen** [comment]
<img width="870" alt="screen shot 2018-05-20 at 12 43 07 pm" src="https://user-images.githubusercontent.com/13535256/40275743-6b400e84-5c2b-11e8-9666-be75e39f83db.png">

**Comment by Shyam-Chen** [comment]
Update to Font Awesome v5 :sweat_smile: :sweat_smile: :sweat_smile:

![screen shot 2018-05-21 at 9 25 11 am](https://user-images.githubusercontent.com/13535256/40286398-28a99442-5cd9-11e8-9bca-90f3936460b9.png)

**Comment by Shyam-Chen** [comment]
#30 Performance
#3 Progressive Web App
#21 Accessibility
#18 SEO
