### ISSUE TITLE
Viewing the page on browser

### ISSUE THREAD

**Issue by nwaughachukwuma** [Shyam-Chen/Vue-Fullstack-Starter#32]
Hey @Shyam-Chen after running `yarn start:app` and `yarn start:api`, how do I get this to run on my browser, or how does this work?

**Comment by nwaughachukwuma** [comment]
Figured it out: localhost:8000 worked for me. Got confused after I tried http://0.0.0.0:8000 and it didn't work. Thanks anyway

**Comment by nwaughachukwuma** [comment]
I have gotten this to work anyway. Used localhost:8000. Was trying 0.0.0.0:8000 for a while and it wasn't working

**Comment by Shyam-Chen** [comment]
`http://0.0.0.0:8000/` is required when you use the container. I can access `http://0.0.0.0:8000/` directly on macOS.
