### ISSUE TITLE
Generate a blank project via Vue CLI

### ISSUE THREAD

**Issue by Shyam-Chen** [Shyam-Chen/Vue-Fullstack-Starter#7]
Vue Fullstack Starter is for practical examples.

```bash
$ yarn global add vue-cli
$ vue init Shyam-Chen/Vue-Fullstack-Template <PROJECT_NAME>
$ cd <PROJECT_NAME>
$ yarn install

# start
$ yarn start:app
$ yarn start:api
```

**Comment by kwame101** [comment]
This is exactly what i was looking for, thanks!!

**Comment by Shyam-Chen** [comment]
I created a simple template that can be accessed from the link below.

https://github.com/Shyam-Chen/Vue-Fullstack-Template
